### PR TITLE
Add AsyncIterator Support

### PR DESCRIPTION
**Pull request by developerworks**
All tests passed in the fork. please test again.

### CODE REVIEW

**Comment by developerworks** [comment]
image

image

`RabbitMqConnectionFactory` will caused create many connections,queues like above

**Comment by developerworks** [comment]
Connetion is reused, but created many queues every connect to rabbitmq

**Comment by cdmbase** [comment]
@developerworks  thanks for the PR. I will push your changes.

**Comment by groundmuffin** [comment]
Is it graphql-js v. ^0.11.0 compatible? The new subscribe method returns Promise that resolves to AsyncIterator. [#918](https://github.com/graphql/graphql-js/pull/918)

**Comment by cdmbase** [comment]
it is using `graphql@^0.10.5`

**Comment by developerworks** [comment]
@groundmuffin The issue is caused by `subscriptions-transport-ws`, i think you could be waiting `subscriptions-transport-ws` to repair this issue https://github.com/apollographql/subscriptions-transport-ws/issues/269

**Pull request merged**
